version: '3.9'

services:
  makizapp_db:
    container_name: java_db
    restart: always
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: makizapp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
