openapi: 3.0.0
info:
  title: Admin API
  version: 1.0.0
  description: API for managing projects and user authentication

paths:
  /admin/projects:
    get:
      summary: Get a list of projects
      description: Returns a list of projects created by the admin.
      responses:
        200:
          description: List of projects successfully retrieved

    post:
      summary: Create a new project
      description: Create a new project within the admin's account.
      requestBody:
        description: Project data to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectMetadata'
      responses:
        201:
          description: Project successfully created
      security:
        - GoogleOAuth2: [admin]

  /admin/projects/{project_id}:
    get:
      summary: Get project metadata
      description: Returns metadata of a specific project such as size on disk, creation date.
      parameters:
        - name: project_id
          in: path
          description: ID of the project to be accessed
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Project metadata successfully retrieved
      security:
        - GoogleOAuth2: [admin]

    delete:
      summary: Delete a project
      description: Delete a project by specifying the project ID to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project to delete.
      responses:
        200:
          description: Project deleted successfully.
        404:
          description: Project not found. The specified project ID does not exist.
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [admin]


  /admin/projects/{project_id}/deletemedia:
    delete:
      summary: Delete media on project
      description: Delete a media by specifying the project ID containing the media to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project containing the picture to be deleted.
      responses:
        200:
          description:  deleted successfully.
        404:
          description: Project not found or invalid permission.
        444:
          description: Picture not found. The project does not contains picture.
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [admin]


  /admin/projects/{project_id}{new_name}/renameProject:
    post:
      summary: Rename a project
      description: Rename a project by specifying the new project name.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the picture.
        - in: path
          name: new_name
          required: true
          schema:
            type: string
          description: The new name of the project.
      responses:
        201:
          description: Picture uploaded successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project and/or picture not found. The specified project ID and/or picture ID does not exist.
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [admin]

  /admin/projects/{project_id}/duplicate:
    post:
      summary: Duplicate a project
      description: Duplicate a project by specifying the project ID to duplicate.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project to duplicate.
      responses:
        201:
          description: Project duplicated successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project not found. The specified project ID does not exist.
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [admin]

  /admin/projects/create:



  /admin/projects/{project_id}{picture_id}/uploadMedia:
    post:
      summary: Upload a picture on a project
      description: Upload a picture on a project by specifying the project ID and the picture ID.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the picture.
        - in: path
          name: picture_id
          required: true
          schema:
            type: string
          description: The ID of the picture to upload to the project.

      responses:
        201:
          description: Picture uploaded successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project and/or picture not found. The specified project ID and/or picture ID does not exist.
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [admin]


components:
  schemas:
    ProjectMetadata:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        size:
          type: integer
        creationDate:
          type: string
      required:
        - name
      example:
        name: "Sample Project"
        description: "This is a sample project."

  securitySchemes:
    GoogleOAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: "https://accounts.google.com/o/oauth2/auth"
          tokenUrl: "https://accounts.google.com/o/oauth2/token"
          scopes:
            admin: Grants access to admin read/write operations
