openapi: 3.0.0
info:
  title: Admin API
  version: 1.0.0
  description: API for managing projects and user authentication

paths:
  /public/projects:
    get:
      summary: Get a list of projects
      description: Returns a list of projects created by the admin.
      responses:
        200:
          description: List of projects as string
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: array
                    items:
                      type: string

  /public/projects/{project_id}/getProjectComposition:
    get:
      summary: Get what media should be played when detecting an image
      description: Returns all element associated with image
      parameters:
        - name: project_id
          in: path
          description: ID of the project to be accessed
          required: true
          schema:
            type: string
      responses:
        200:
          description:  "Element in the form imageId:[mediaID1,mediaID2...]"
          content:
            application/json:
              schema:
                type: object
                properties:
                  medias:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string

  /public/projects/{project_id}/getAllMediaNameInProject:
      get:
        summary: Get project element
        description: Returns the id of all element in project along with associated type
        parameters:
          - name: project_id
            in: path
            description: ID of the project to be accessed
            required: true
            schema:
              type: string
        responses:
          200:
            description: Return all project element list
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    medias:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          type:
                            type: string

  /public/projects/{project_id}/getLocallyStoredImage:
    get:
      summary: Get an image
      description: Get an image stored on server
      parameters:
        - name: project_id
          in: path
          description: ID of the project to be accessed
          required: true
          schema:
            type: string
        - in: query
          name: media_id
          required: true
          schema:
            type: string
          description: The ID of the media to be accessed.
      responses:
        200:
          description: The media, in binary form
          content:
            image/jpeg:
              schema:
                  type: string
                  format: binary
        404:
          description: image not found

  /public/projects/{project_id}/getLocallyStoredSound:
    get:
      summary: Get a sound file
      description: Get sound stored on server
      parameters:
        - name: project_id
          in: path
          description: ID of the project to be accessed
          required: true
          schema:
            type: string
        - in: query
          name: media_id
          required: true
          schema:
            type: string
          description: The ID of the media to be accessed.
      responses:
        200:
          description: The media, in binary form
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary

  /admin/projects/:
    post:
      summary: Create a new project
      description: Create a new project within the admin account.
      parameters:
        - name: project_id
          in: query
          description: ID of the project to be created
          required: true
          schema:
            type: string

      responses:
        200:
          description: OK
        400:
          description: Invalid id
        409:
          description: If resource already exist
      security:
        - GoogleOAuth2: [admin]

  /admin/projects/{project_id}/:
    get:
      summary: Get project metadata
      description: Returns metadata of a specific project such as size on disk, creation date.
      parameters:
        - name: project_id
          in: path
          description: ID of the project to be accessed
          required: true
          schema:
            type: string
      responses:
        200:
          description: Project metadata successfully retrieved
        400:
          description: Invalid id
      security:
        - GoogleOAuth2: [admin]
    delete:
      summary: Delete a project
      description: Delete a project by specifying the project ID to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project to delete.
      responses:
        200:
          description: OK
        400:
          description: Invalid id
        404:
          description: Project not found. The specified project ID does not exist.
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [admin]
    post:
      summary: Rename a project
      description: Rename a project by specifying the new project name.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the picture.
        - in: query
          name: new_name
          required: true
          schema:
            type: string
          description: The new name of the project.
      responses:
        200:
          description: OK.
        404:
          description: Unauthorized or not found.
        409:
          description: If resource already exist
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [ admin ]

    put:
      summary: Create a new project
      description: Create a new project within the admin's account.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
      responses:
        201:
          description: Project successfully created
      security:
        - GoogleOAuth2: [admin]

  /admin/projects/{project_id}/addVideo:
    post:
      summary: Upload a video on a project
      description: Upload a video on a project
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the project.
        - in: query
          name: videoName
          required: true
          schema:
            type: string
        - in: query
          name: url
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: Video uploaded successfully.
        400:
          description: Invalid name or unsupported media
        404:
          description: Project and/or picture not found. The specified project ID and/or picture ID does not exist.
        409:
          description: If resource already exist
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [admin]

  /admin/projects/{project_id}/addImage:
    post:
      summary: Upload a picture on a project
      description: Upload a picture on a project
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the picture.
        - in: query
          name: name
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          image/jpeg:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: Picture uploaded successfully.
        400:
          description: Invalid name or unsupported media
        404:
          description: Project and/or picture not found. The specified project ID and/or picture ID does not exist.
        409:
          description: If resource already exist
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [admin]

  /admin/projects/{project_id}/addSound:
    post:
      summary: Upload sound on a project
      description: Upload sound on a project
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the picture.
        - in: query
          name: name
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          audio/mp3:
            schema:
              type: string
              format: binary

      responses:
        200:
          description: Picture uploaded successfully.
        400:
          description: Invalid name or unsupported media
        404:
          description: Project and/or picture not found. The specified project ID and/or picture ID does not exist.
        409:
          description: If resource already exist
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [ admin ]

  /admin/projects/{project_id}/{media_id}/rename:

    post:
      summary: Rename media on project
      description: Rename a media by specifying the project ID containing the media to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project containing the picture to be renamed.
        - in: path
          name: media_id
          required: true
          schema:
            type: string
          description: The ID of the media to be deleted.
      responses:
        200:
          description: Rename successfully.
        400:
          description: Project not found or invalid permission.
        404:
          description: Picture not found. The project does not contains picture.
        409:
          description: If resource already exist
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [ admin ]

    delete:
      summary: Delete media on project
      description: Delete a media by specifying the project ID containing the media to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project containing the picture to be deleted.
        - in: path
          name: media_id
          required: true
          schema:
            type: string
          description: The ID of the media to be deleted.
      responses:
        200:
          description: deleted successfully.
        404:
          description: Project not found or invalid permission.
        409:
          description: If resource already exist
        5XX:
          description: Unexpected error
      security:
        - GoogleOAuth2: [ admin ]


components:

  securitySchemes:
    SpringOAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: "http://localhost:9000/oauth2/authorize"
          tokenUrl: "http://localhost:9000/oauth2/token"
          scopes:
            admin: Grants access to admin read/write operations
