openapi: 3.0.0
info:
  title: Admin API
  version: 1.0.0
  description: API for managing projects and user authentication

paths:
  /admin/projects:
    get:
      summary: Get a list of projects
      description: Returns a list of projects created by the admin.
      responses:
        200:
          description: List of projects successfully retrieved
      security:
        - GoogleOAuth2: []

    post:
      summary: Create a new project
      description: Create a new project within the admin's account.
      requestBody:
        description: Project data to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        201:
          description: Project successfully created
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}:
    get:
      summary: Get project details
      description: Returns details of a specific project.
      parameters:
        - name: project_id
          in: path
          description: ID of the project to be accessed
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Project details successfully retrieved
      security:
        - GoogleOAuth2: []

    put:
      summary: Update project details
      description: Update the details of a specific project.
      parameters:
        - name: project_id
          in: path
          description: ID of the project to be accessed
          required: true
          schema:
            type: integer
      requestBody:
        description: Updated project data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        200:
          description: Project details successfully updated
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}/delete:
    delete:
      summary: Delete a project
      description: Delete a project by specifying the project ID to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project to delete.
      responses:
        201:
          description: Project deleted successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project not found. The specified project ID does not exist.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}/deletePicture:
    delete:
      summary: Delete picture on project
      description: Delete a picture by specifying the project ID containing the picture to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project containing the picture to be deleted.
      responses:
        201:
          description: Picture deleted successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project not found. The specified project ID does not exist.
        444:
          description: Picture not found. The project does not contains picture.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}/deleteVideo:
    delete:
      summary: Delete video on project
      description: Delete a video by specifying the project ID containing the video to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project containing the video to be deleted.
      responses:
        201:
          description: Video deleted successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project not found. The specified project ID does not exist.
        444:
          description: Video not found. The project does not contains video.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}/deleteSong:
    delete:
      summary: Delete song on project
      description: Delete a song by specifying the project ID containing the song to delete.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project containing the song to be deleted.
      responses:
        201:
          description: Song deleted successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project not found. The specified project ID does not exist.
        444:
          description: Song not found. The project does not contains song.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}{new_name}/renameProject:
    post:
      summary: Rename a project
      description: Rename a project by specifying the new project name.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the picture.
        - in: path
          name: new_name
          required: true
          schema:
            type: string
          description: The new name of the project.
      responses:
        201:
          description: Picture uploaded successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project and/or picture not found. The specified project ID and/or picture ID does not exist.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}/duplicate:
    post:
      summary: Duplicate a project
      description: Duplicate a project by specifying the project ID to duplicate.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project to duplicate.
      responses:
        201:
          description: Project duplicated successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project not found. The specified project ID does not exist.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []

  /admin/projects/create:
    post:
      summary: Create a project
      description: Create a new project by specifying the project name.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Project name.
      responses:
        201:
          description: Project created successfully.
        400:
          description: Bad request. Check the input data.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []


  /admin/projects/{project_id}{picture_id}/uploadPicture:
    post:
      summary: Upload a picture on a project
      description: Upload a picture on a project by specifying the project ID and the picture ID.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the picture.
        - in: path
          name: picture_id
          required: true
          schema:
            type: string
          description: The ID of the picture to upload to the project.
      responses:
        201:
          description: Picture uploaded successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project and/or picture not found. The specified project ID and/or picture ID does not exist.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}{video_id}/uploadVideo:
    post:
      summary: Upload a video on a project
      description: Upload a video on a project by specifying the project ID and the video ID.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the video.
        - in: path
          name: video_id
          required: true
          schema:
            type: string
          description: The ID of the video to upload to the project.
      responses:
        201:
          description: Video uploaded successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project and/or video not found. The specified project ID and/or video ID does not exist.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []

  /admin/projects/{project_id}{song_id}/uploadSong:
    post:
      summary: Upload a song on a project
      description: Upload a song on a project by specifying the project ID and the song ID.
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            type: string
          description: The ID of the project where to upload the song.
        - in: path
          name: song_id
          required: true
          schema:
            type: string
          description: The ID of the song to upload to the project.
      responses:
        201:
          description: Song uploaded successfully.
        401:
          description: Unauthorized. You do not have the necessary permissions.
        404:
          description: Project and/or song not found. The specified project ID and/or song ID does not exist.
        500:
          description: Internal server error. Please try again later.
      security:
        - GoogleOAuth2: []



components:
  schemas:
    Project:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
      example:
        name: "Sample Project"
        description: "This is a sample project."

  securitySchemes:
    GoogleOAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: "https://accounts.google.com/o/oauth2/auth"
          tokenUrl: "https://accounts.google.com/o/oauth2/token"
          scopes:
            openid: OpenID Connect
            profile: View user profile
