spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/makizapp
    username: admin
    password: password

server:
  ssl:
    key-store: file:src/main/resources/keystore.p12
    key-store-password: abcdef
    key-store-type: PKCS12
    key-alias: makizapp