spring:
  security:
    oauth2:

      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/

  datasource:
    url: jdbc:postgresql://localhost:5432/makizapp
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
