spring:
  profiles:
    active: development

  datasource:
    url: jdbc:postgresql://localhost:5432/makizapp
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null

server:
  address: 192.168.235.31
  port: 8080
  ssl:
    key-store: keystore.p12
    key-store-password: abcdef
    key-store-type: PKCS12
    key-alias: makizapp

