spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9001

  datasource:
    url: jdbc:postgresql://localhost:5432/makizapp
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
