spring:
  profiles:
    active: development

  datasource:
    url: jdbc:postgresql://localhost:5432/makizapp
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null

server:
  address: 10.0.2.15
  port: 8080
