@startuml

title Admin sequence diagram

actor "Admin" as A

participant "App" as AP
participant "Database" as DB

A -> AP : Login
activate AP
AP -> AP : Routes to admin dashboard
A -> AP : Create a new project
AP -> DB : Stores in project table
deactivate AP

alt Admin uploads a media

A -> AP : Upload an image
activate AP
AP -> DB : Stores as an ImageAsset
deactivate AP

A -> AP : Upload a sound
activate AP
AP -> DB : Stores as an SoundAsset
deactivate AP

A -> AP : Upload a video
activate AP
AP -> DB : Stores a video URL
deactivate AP

end

@enduml