@startuml

title User sequence diagram

actor "User" as U

participant "App" as AP
participant "Database" as DB

U -> AP : Connection via a URL
activate AP
AP -> DB : Fetch elements
DB -> AP :
AP -> AP : Return User's page
deactivate

U -> AP : Scan an image
activate AP
AP -> AP : Found marker on the camera
AP -> U : Play video associate to the image
deactivate

@enduml
