server:
  port: 9001

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "makizart"
              client-secret: "{bcrypt}$2a$10$PhD9krclE/ileLlCZXJcGuGq4qj0Y20/R9UeoqaN0eClJEzl9py5q"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "admin"
            require-authorization-consent: true
  #datasource:
   # url: jdbc:postgresql://localhost:5432/makizapp
   # username: admin
   # password: password
