server:
  port: 9001

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "makizart"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/admin"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/#/admin"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
  #datasource:
   # url: jdbc:postgresql://localhost:5432/makizapp
   # username: admin
   # password: password
