name: CI/CD pipeline

on:
  push:
    branches:
      - containerization

jobs:
  check-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Postgres instance runtime check, create the database if needed
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.58.98.24
          username: root
          key: ${{ secrets.SSH_PRIVATE }}
          script: |
            sudo -i -u postgres
            psql -d postgres -c "CREATE DATABASE makizapp;" 2> /dev/null  
            \q
            exit

  deploy:
    needs: check-database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Auth to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: makizapp
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Run the backend deployment script
        run: |
          gcloud builds triggers run deploy-cloud-run --region=us-central1 --branch=containerization
          
